# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 123dde9c5d9bde33b17ac43dcef4bf1b4792328a15ffc9ed709ba967b8eda04db1fc72c879ef04e7232f54ff561a9ca7b5038ecbb67ccae7b11c248cfdacb26a

test:
  secret_key_base: 02d0bcd0258a58644a0c23d38b6d0812f99aa635ca7bd7ead2d3841e1f468d22f6890d4eb2879dd89bce8acebe752be02729695650f8ac7fa8ba8e176a381919

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
